name: nasa
description: "Astronomy Picture of the Day"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Network
  dio: ^5.7.0
  internet_connection_checker: ^1.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Utils
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  mockito: ^5.4.4
  mocktail: ^1.0.3  # Alternative to mockito, more concise syntax
  http_mock_adapter: ^0.6.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
