// Mocks generated by Mockito 5.4.4 from annotations
// in nasa/test/data/repository/apod_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa/src/core/network/network_info.dart' as _i7;
import 'package:nasa/src/data/model/apod_hive_model.dart' as _i6;
import 'package:nasa/src/data/repository/contracts/apod_local_provider.dart'
    as _i5;
import 'package:nasa/src/data/repository/contracts/apod_remote_provider.dart'
    as _i3;
import 'package:nasa/src/domain/entity/apod.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApod_0 extends _i1.SmartFake implements _i2.Apod {
  _FakeApod_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodRemoteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodRemoteProvider extends _i1.Mock
    implements _i3.ApodRemoteProvider {
  @override
  _i4.Future<List<_i2.Apod>> getApodList(
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApodList,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Apod>>.value(<_i2.Apod>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Apod>>.value(<_i2.Apod>[]),
      ) as _i4.Future<List<_i2.Apod>>);

  @override
  _i4.Future<_i2.Apod> getApodByDate(String? date) => (super.noSuchMethod(
        Invocation.method(
          #getApodByDate,
          [date],
        ),
        returnValue: _i4.Future<_i2.Apod>.value(_FakeApod_0(
          this,
          Invocation.method(
            #getApodByDate,
            [date],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Apod>.value(_FakeApod_0(
          this,
          Invocation.method(
            #getApodByDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Apod>);
}

/// A class which mocks [ApodLocalProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodLocalProvider extends _i1.Mock implements _i5.ApodLocalProvider {
  @override
  _i4.Future<List<_i6.ApodHiveModel>> getApodList() => (super.noSuchMethod(
        Invocation.method(
          #getApodList,
          [],
        ),
        returnValue:
            _i4.Future<List<_i6.ApodHiveModel>>.value(<_i6.ApodHiveModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.ApodHiveModel>>.value(<_i6.ApodHiveModel>[]),
      ) as _i4.Future<List<_i6.ApodHiveModel>>);

  @override
  _i4.Future<_i6.ApodHiveModel?> getApodByDate(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApodByDate,
          [date],
        ),
        returnValue: _i4.Future<_i6.ApodHiveModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.ApodHiveModel?>.value(),
      ) as _i4.Future<_i6.ApodHiveModel?>);

  @override
  _i4.Future<void> cacheApodList(List<_i6.ApodHiveModel>? apodList) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheApodList,
          [apodList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheApod(_i6.ApodHiveModel? apod) => (super.noSuchMethod(
        Invocation.method(
          #cacheApod,
          [apod],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
