// Mocks generated by Mockito 5.4.4 from annotations
// in nasa/test/presentation/feature/apod_list/apod_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i14;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa/src/core/error/failures.dart' as _i8;
import 'package:nasa/src/domain/entity/apod.dart' as _i9;
import 'package:nasa/src/domain/repository/apod_repository.dart' as _i2;
import 'package:nasa/src/domain/use_case/clear_cache.dart' as _i11;
import 'package:nasa/src/domain/use_case/get_apod_list.dart' as _i6;
import 'package:nasa/src/domain/use_case/search_apod.dart' as _i10;
import 'package:nasa/src/presentation/feature/apod_list/controller/apod_list_controller.dart'
    as _i12;
import 'package:nasa/src/presentation/feature/apod_list/model/apod_ui_model.dart'
    as _i13;
import 'package:nasa/src/presentation/feature/apod_list/state/apod_list_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApodRepository_0 extends _i1.SmartFake
    implements _i2.ApodRepository {
  _FakeApodRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApodListState_2 extends _i1.SmartFake implements _i4.ApodListState {
  _FakeApodListState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScrollController_3 extends _i1.SmartFake
    implements _i5.ScrollController {
  _FakeScrollController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetApodList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApodList extends _i1.Mock implements _i6.GetApodList {
  MockGetApodList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApodRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApodRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApodRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>> call(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>>.value(
            _FakeEither_1<_i8.Failure, List<_i9.Apod>>(
          this,
          Invocation.method(
            #call,
            [
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>>);
}

/// A class which mocks [SearchApods].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchApods extends _i1.Mock implements _i10.SearchApods {
  MockSearchApods() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApodRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApodRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApodRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>> call(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [query],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>>.value(
            _FakeEither_1<_i8.Failure, List<_i9.Apod>>(
          this,
          Invocation.method(
            #call,
            [query],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, List<_i9.Apod>>>);
}

/// A class which mocks [ClearCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCache extends _i1.Mock implements _i11.ClearCache {
  MockClearCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApodRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApodRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApodRepository);

  @override
  _i7.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i5.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i5.Route<dynamic>? newRoute,
    _i5.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApodListController].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodListController extends _i1.Mock
    implements _i12.ApodListController {
  MockApodListController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ApodListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeApodListState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.ApodListState);

  @override
  _i5.ScrollController get scrollController => (super.noSuchMethod(
        Invocation.getter(#scrollController),
        returnValue: _FakeScrollController_3(
          this,
          Invocation.getter(#scrollController),
        ),
      ) as _i5.ScrollController);

  @override
  List<_i13.ApodUiModel> get uiModels => (super.noSuchMethod(
        Invocation.getter(#uiModels),
        returnValue: <_i13.ApodUiModel>[],
      ) as List<_i13.ApodUiModel>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> loadApods({bool? refresh = false}) => (super.noSuchMethod(
        Invocation.method(
          #loadApods,
          [],
          {#refresh: refresh},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadMore() => (super.noSuchMethod(
        Invocation.method(
          #loadMore,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> searchApodsList(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchApodsList,
          [query],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
